#!/bin/bash
echo "hello Redis"

echo $HOME

cd $HOME/build/redis

docker_login=`aws ecr get-login --region us-west-2 `
$docker_login

docker build -t web_redis .

docker tag web_redis:latest 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_redis:latest 
docker push 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_redis:latest