#!/bin/bash

echo $HOME

cd $HOME/build/biomioAi

docker_login=`aws ecr get-login --region us-west-2`

$docker_login

docker build --build-arg "CACHE_DATE=$(date)" -t web_nginx .
docker tag web_nginx:latest 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_nginx:latest 
docker push 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_nginx:latest