#!/bin/bash
echo "hello OpenIdPorvider"

echo $HOME

cd $HOME/build/openidprovider

docker_login=`aws ecr get-login --region us-west-2`
$docker_login

docker build --build-arg "CACHE_DATE=$(date)" -t web_openidprovider .

docker tag web_openidprovider:latest 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_openidprovider:latest 
docker push 143475945728.dkr.ecr.us-west-2.amazonaws.com/web_openidprovider:latest
